import esbuild from "esbuild";
import process from "process";
import { mkdirSync } from "fs";

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

mkdirSync("dist", { recursive: true });

/** @type {import("esbuild").BuildOptions} */
const opts = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "dist/main.js",
  format: "cjs",
  target: "es2020",
  platform: "browser",
  sourcemap: prod ? false : "inline",
  minify: prod,
  banner: { js: banner },
  external: ["obsidian"]
};

if (watch) {
  const ctx = await esbuild.context(opts);
  await ctx.watch();
  console.log("watching...");
} else {
  await esbuild.build(opts);
  console.log("built");
}